# Name:
# SBUID: 

# ---------------------------- Exercise 1: The Grade Calculator ----------------------------
# TODO: Complete the implementation of request_score(), compute_average(), and compute_grade().

# Function to request scores from the user
def request_score():
    # Your code here
    ...

# Function to compute the average score
def compute_average():
    # Your code here
    ...

# Function to compute the final grade
def compute_grade():
    # Your code here
    ...

# ---------------------------- Exercise 2: The modern Architect ----------------------------
# TODO: Complete the implementation of calculate_frustum_volume() and calculate_ac_units().

# Function to calculate the volume of a frustum
def calculate_frustum_volume():
    # Your code here
    ...

# Function to calculate the number of AC units needed
def calculate_ac_units():
    # Your code here
    ...

# ---------------------------- Exercise 3: The Solar Panel Problem ----------------------------
# TODO: Complete the implementation of calculate_triangle_area() and calculate_energy().

# Function to calculate the area of a triangle
def calculate_triangle_area():
    # Your code here
    ...

# Function to calculate the energy generated by the solar panels
def calculate_energy():
    # Your code here
    ...

# ---------------------------- Main Function ----------------------------
def main():
    
    # Exercise I
    ...

    # Exercise II
    h = 5 
    R = 3
    r =2 
    ...

    # Exercise III
    a = 3
    b = 2.5
    c = 4
    ...

if __name__ == "__main__":
    main()
